단어 -> 정수인코딩 -> 룩업테이블 -> 임베딩

In [7]:
 from tensorflow.keras.preprocessing.text import Tokenizer
 from tensorflow.keras.preprocessing.sequence import pad_sequences
 import numpy as np

In [8]:
sentences = ['nice great best amazing', 'stop lies', 'pitiful nerd', 'excellent work', 'supreme quality', 'bad', 'highly respectable']
y_train = [1, 0, 0, 1, 1, 0, 1]

In [9]:
t = Tokenizer() #토큰화
t.fit_on_texts(sentences)
vocab_size = len(t.word_index) + 1

print(vocab_size)

16


In [10]:
X_encoded = t.texts_to_sequences(sentences) #정수 인코딩
print(X_encoded)

[[1, 2, 3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13], [14, 15]]


In [11]:
max_len = max(len(l) for l in X_encoded)
print(max_len) #패딩하기위해서 가장 긴 문장의 길이

4


In [12]:
X_train = pad_sequences(X_encoded, maxlen=max_len, padding='post') #padding
y_train=np.array(y_train)
print(X_train)

[[ 1  2  3  4]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]
 [11 12  0  0]
 [13  0  0  0]
 [14 15  0  0]]


In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

model = Sequential()
model.add(Embedding(vocab_size,4,input_length=max_len))
model.add(Flatten()) #dense입력을 위함
model.add(Dense(1,activation='sigmoid'))

In [14]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])
model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
1/1 - 1s - loss: 0.6942 - acc: 0.5714
Epoch 2/100
1/1 - 0s - loss: 0.6926 - acc: 0.5714
Epoch 3/100
1/1 - 0s - loss: 0.6910 - acc: 0.5714
Epoch 4/100
1/1 - 0s - loss: 0.6894 - acc: 0.5714
Epoch 5/100
1/1 - 0s - loss: 0.6879 - acc: 0.5714
Epoch 6/100
1/1 - 0s - loss: 0.6863 - acc: 0.5714
Epoch 7/100
1/1 - 0s - loss: 0.6847 - acc: 0.5714
Epoch 8/100
1/1 - 0s - loss: 0.6831 - acc: 0.5714
Epoch 9/100
1/1 - 0s - loss: 0.6815 - acc: 0.5714
Epoch 10/100
1/1 - 0s - loss: 0.6799 - acc: 0.7143
Epoch 11/100
1/1 - 0s - loss: 0.6783 - acc: 0.8571
Epoch 12/100
1/1 - 0s - loss: 0.6767 - acc: 0.8571
Epoch 13/100
1/1 - 0s - loss: 0.6751 - acc: 0.8571
Epoch 14/100
1/1 - 0s - loss: 0.6735 - acc: 0.8571
Epoch 15/100
1/1 - 0s - loss: 0.6719 - acc: 0.8571
Epoch 16/100
1/1 - 0s - loss: 0.6703 - acc: 0.8571
Epoch 17/100
1/1 - 0s - loss: 0.6687 - acc: 0.8571
Epoch 18/100
1/1 - 0s - loss: 0.6670 - acc: 0.8571
Epoch 19/100
1/1 - 0s - loss: 0.6654 - acc: 0.8571
Epoch 20/100
1/1 - 0s - loss: 0.6638 - a

In [15]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove*.zip

--2021-05-03 12:07:16--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2021-05-03 12:07:16--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2021-05-03 12:07:16--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip.1’

glove

In [20]:
import numpy as np
embedding_dict = dict()
f = open('glove.6B.100d.txt', encoding="utf8")

for line in f:
    word_vector = line.split()
    word = word_vector[0]
    word_vector_arr = np.asarray(word_vector[1:], dtype='float32') # 100개의 값을 가지는 array로 변환
    embedding_dict[word] = word_vector_arr
f.close()
print('%s개의 Embedding vector가 있습니다.' % len(embedding_dict))

400000개의 Embedding vector가 있습니다.


In [17]:
print(embedding_dict['respectable'])
print(len(embedding_dict['respectable']))

[-0.049773   0.19903    0.10585    0.1391    -0.32395    0.44053
  0.3947    -0.22805   -0.25793    0.49768    0.15384   -0.08831
  0.0782    -0.8299    -0.037788   0.16772   -0.45197   -0.17085
  0.74756    0.98256    0.81872    0.28507    0.16178   -0.48626
 -0.006265  -0.92469   -0.30625   -0.067318  -0.046762  -0.76291
 -0.0025264 -0.018795   0.12882   -0.52457    0.3586     0.43119
 -0.89477   -0.057421  -0.53724    0.25587    0.55195    0.44698
 -0.24252    0.29946    0.25776   -0.8717     0.68426   -0.05688
 -0.1848    -0.59352   -0.11227   -0.57692   -0.013593   0.18488
 -0.32507   -0.90171    0.17672    0.075601   0.54896   -0.21488
 -0.54018   -0.45882   -0.79536    0.26331    0.18879   -0.16363
  0.3975     0.1099     0.1164    -0.083499   0.50159    0.35802
  0.25677    0.088546   0.42108    0.28674   -0.71285   -0.82915
  0.15297   -0.82712    0.022112   1.067     -0.31776    0.1211
 -0.069755  -0.61327    0.27308   -0.42638   -0.085084  -0.17694
 -0.0090944  0.1109     0.

In [18]:
vocab_size = 16
embedding_matrix=np.zeros((vocab_size,100)) #단어집합의 크기의 행과 임베딩 벡터의 크기의 열

print(t.word_index)

In [21]:
for word,i in t.word_index():
 temp = embedding_dict.get(word) 
 if temp is not None:
   embedding_matrix[i] = embedding #인덱스에 임베딩 벡터 넣어주기

TypeError: ignored

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten
model = Sequential()
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=max_len, trainable=False)